# Day-13

# NumPy part 2

# Slicing of numPy arrays

In [9]:
import numpy as np

In [10]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [19]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


# Slicing in 2D array

In [20]:
a=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[1,1:4])

[70 80 90]


In [21]:
a=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[0,0:4])

[10 20 30 40]


In [47]:
arr = np.array([[[1,2,3,4],[10,20,30,40],[5,6,7,8]]])     #3D 
print(arr[0:,0,1])

[2]


In [67]:
arr = np.array([[[1,2,3,4],[10,20,30,40],[5,6,7,8]]])     #3D 
print(arr[0, 1, :])

[10 20 30 40]


In [68]:
arr = np.array([[[1,2,3,4],[10,20,30,40],[5,6,7,8]]])     #3D 
print(arr[0, 2, :])

[5 6 7 8]


# Checking the data type of an array.

In [63]:
arr=np.array([1,2,3,4])
print(arr.dtype)

int32


In [23]:
arr=np.array(['animal','bat','cat'])
print(arr.dtype)

<U6


# Creating arrays with a defined data type

In [32]:
arr = np.array([1,2,3,4], dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


# Create an array with data types 4 bytes integer.

In [35]:
arr = np.array([1,2,3,4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# Numpy array Shape

the shape of an array is the number of an elements in each dimension.

# print the shape of 2D array

In [36]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [45]:
arr = np.array([[[1,2,3,4],[10,20,30,40],[5,6,7,8]]])     #3D 
print(arr.shape)

(1, 3, 4)


# Joining Numpy Arrays

In [70]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


# Join 2D arrays

In [71]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [72]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# join 3D arrays

In [73]:
array1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

# Concatenate along a specific axis (e.g., along the z-axis, which is the 2nd dimension)
result = np.concatenate((array1, array2), axis=2)

print(result)

[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


In [76]:
array1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

result = np.concatenate((array1, array2), axis=1)

print(result)

[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]


# Splitting Numpy Arrays

# splitting the array in 3 parts

In [77]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


# splitting the array in 4 parts

In [78]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Ravel and Flatten

Converts multidimensional array into 1 D array.

In [92]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])  #3D
print(m)
print("dimension is",m.ndim)
n = m.ravel()
print(n)
print("now the new dimension is", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is 3
[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


In [93]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("dimension is",m.ndim)
n = m.flatten()  #ravel and flatten work same.
print(n)
print("now the new dimension is", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is 3
[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


In [94]:
c = np.array([[[[1,2,3],[78,79,80],[45,46,47],[34,47,55]]]])  #4D
print(c)
print("dimension is",c.ndim)
n = c.ravel()
print(n)
print("now the new dimension is", n.ndim)

[[[[ 1  2  3]
   [78 79 80]
   [45 46 47]
   [34 47 55]]]]
dimension is 4
[ 1  2  3 78 79 80 45 46 47 34 47 55]
now the new dimension is 1


# Unique Function

In [101]:
k = np.array([12,3,4,6,7,64,65,7,9,34,66,88,23,3,7,12,64])
print(k)
x=np.unique(k) #unique value
print(x)

[12  3  4  6  7 64 65  7  9 34 66 88 23  3  7 12 64]
[ 3  4  6  7  9 12 23 34 64 65 66 88]


In [102]:
k = np.array([12,3,4,6,7,64,65,7,9,34,66,88,23,3,7,12,64])
print(k)
x=np.unique(k, return_index=True) #index position
print(x)

[12  3  4  6  7 64 65  7  9 34 66 88 23  3  7 12 64]
(array([ 3,  4,  6,  7,  9, 12, 23, 34, 64, 65, 66, 88]), array([ 1,  2,  3,  4,  8,  0, 12,  9,  5,  6, 10, 11], dtype=int64))


In [103]:
k = np.array([12,3,4,6,7,64,65,7,9,34,66,88,23,3,7,12,64])
print(k)
x=np.unique(k, return_index=True, return_counts=True) #repeat time
print(x)

[12  3  4  6  7 64 65  7  9 34 66 88 23  3  7 12 64]
(array([ 3,  4,  6,  7,  9, 12, 23, 34, 64, 65, 66, 88]), array([ 1,  2,  3,  4,  8,  0, 12,  9,  5,  6, 10, 11], dtype=int64), array([2, 1, 1, 3, 1, 2, 1, 1, 2, 1, 1, 1], dtype=int64))


# Delete

In [105]:
a = np.array([12,13,14,15]) #1D
d = np.delete(a, [1])
print(d)

[12 14 15]


In [112]:
x = np.array([[2,3,4,5],[6,7,8,9],[3,4,6,9]]) #2D
print(x)
print("dimension is:",x.ndim)
m = np.delete(x, 2, axis=0)
print()
print(m)

[[2 3 4 5]
 [6 7 8 9]
 [3 4 6 9]]
dimension is: 2

[[2 3 4 5]
 [6 7 8 9]]


In [113]:
x = np.array([[2,3,4,5],[6,7,8,9],[3,4,6,9]]) #2D
print(x)
print("dimension is:",x.ndim)
m = np.delete(x, 0, axis=0)
print()
print(m)

[[2 3 4 5]
 [6 7 8 9]
 [3 4 6 9]]
dimension is: 2

[[6 7 8 9]
 [3 4 6 9]]


In [120]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) #3D
print(x)
print("dimension is:",x.ndim)
m = np.delete(x, 2, axis=2)
print()
print(m)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is: 3

[[[1 2]
  [4 5]
  [7 8]]]
